services:
  - type: web
    name: cms-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
